### ISSUE TITLE
where to see the raw log?

### ISSUE THREAD

**Issue by mw66** [fbertram/TuringTrader#18]
Hi, in my algorithm,

I want to print out some debug info, similar to this one:

 Output.WriteLine("Idle Cash = {0:P2}", Cash);

but where I can see the raw log file?

Thanks for the great library!

**Comment by fbertram** [comment]
TuringTrader has three different levels of output: info, warning, and error. You can set which ones to print in the main window's setting dialog > general > console output. When launching TuringTrader, you can see the current console mode printed along with the versions, and the home path.

I recommend using the functions Output.WriteInfo, Output.WriteWarning, and Output.ThrowError, instead of Output.WriteLine. Any output written with Output.WriteLine will always be displayed, with no option to suppress it, which may clutter the window.

All output goes into the main window console; TuringTrader does not create a log file. If that's what you need, you can do so by adding an event handler to Output.WriteEvent. See this example here: https://github.com/fbertram/TuringTrader/blob/develop/More/TuringTrader.CustomApp/Program.cs

Hope this helps!
