### ISSUE TITLE
FRED DataSource problem

### ISSUE THREAD

**Issue by moieric11** [fbertram/TuringTrader#4]
Hello

When I try Keller's LAA strategy, I've got this error on the log, when I debug the program, the source from fred seems to download, and is stored on the cache directory. I don't understand what the problem ?.

running algorithm Keller's LAA
DataSourceYahoo: retrieving meta for IWD
DataSourceFred: retrieving meta for fred:UNRATE
DataSourceYahoo: loading data for IWD... finished after 0,9 seconds
DataSourceFred: loading data for fred:UNRATE... finished after 0,4 seconds
EXCEPTION: DataSourceFred: failed to load quotes for fred:UNRATE, Object reference not set to an instance of an object.   at TuringTrader.Simulator.DataSourceCollection.DataSourceFred.LoadData(DateTime startTime, DateTime endTime) in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader.Simulator\DataSources\DataSourceFred.cs:line 367
   at TuringTrader.Simulator.SimulatorCore.get_SimTimes()+MoveNext() in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader.Simulator\Core\SimulatorCore.cs:line 420
   at TuringTrader.BooksAndPubs.Keller_LAA_Core.Run()
   at TuringTrader.MainWindow.<>c__DisplayClass35_0.<RunButton_Click>g__uiThread|1() in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader\MainWindow.xaml.cs:line 540
finished algorithm Keller's LAA after 3,4 seconds
EXCEPTION: Plotter: no data to plot   at TuringTrader.Simulator.Plotter.OpenWith(String pathToTemplateFile) in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader.Simulator\Core\Plotter.cs:line 239
   at TuringTrader.BooksAndPubs.Keller_LAA_Core.Report()
   at TuringTrader.MainWindow.<ReportButton_Click>b__36_0() in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader\MainWindow.xaml.cs:line 593

**Comment by fbertram** [comment]
thanks a lot for reporting the issue. Unfortunately, I cannot reproduce this on my end. I tried installing binary v0.12b1 in a fresh sandbox and things seem to work fine. Looking at your logfile, I suspect that this issue is somehow related to the localization of time/ date formats. 

I have the following questions for you:
- did you compile TuringTrader from source, or are you seeing this issue with the binary? If source: which branch? If binary: v0.12b1?
- on which version of Windows are you running?
- what are your regional formats for numbers and dates? See Windows Settings / Time & Language / Region

Thanks!

**Comment by moieric11** [comment]
thank you Felix for your feedback and your work !

Yes, I finally solved the problem, as you told me, I changed my regional settings I'm in European date format (dd-mm-yyyy), and I tested the United States date format (mm-dd-yyyy). It Works.

At the source code level I finally found a solution to force the US format without changing my settings. Everything seems to work properly. I don't know if this is the best place to put the code, but it seems to work fine. It seems to act at the level of the current thread

In the file TuringTrader\MainWindow.xaml.cs, add these two lines and include that library
```C#
            //*** add this library ***
using System.Globalization;


public MainWindow()
        {
            //*** add these two lines ***
            CultureInfo currentCulture = Thread.CurrentThread.CurrentCulture;
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");
           //*** end ***
            InitializeComponent();
            DataContext = this;

            MenuItems = new ObservableCollection<MenuItemViewModel>();

            //--- redirect log output
            Output.WriteEvent += WriteEventHandler;

            //--- set timer event
            _dispatcherTimer.Tick += new EventHandler(DispatcherTimer_Tick);
            _dispatcherTimer.Tick += new EventHandler(Initialize_Once);
            _dispatcherTimer.Interval = TimeSpan.FromMilliseconds(200);
            _dispatcherTimer.Start();
        }

**Comment by fbertram** [comment]
thank you so much for your help, this is highly appreciated. Knowing what caused the issue will help me fix it for good.

When it comes to setting the culture, I am generally using Culture.InvariantCulture to parse dates. We should make it a habit to set the culture in the simulator engine, not the application. The reason is, that the engine should work in a context other than the TuringTrader application. Examples of that would include internal applications I use at Bertram Solutions, as well as the backend for TuringTrader.com. From that perspective, the place you suggested above is not ideal.

I will check this on my end, but I assume that the exception is thrown while parsing dates here: https://github.com/fbertram/TuringTrader/blob/dda16009903b3caab66afc3200c7152baeb506c9/TuringTrader.Simulator/DataSources/DataSourceFred.cs#L321

Best regards, Felix

**Comment by moieric11** [comment]
I figured out where the problem was coming from. No problem with your date and time variables, they already contain the necessary InvariantCulture code, and it works. Double is a comma in foreign format, and it catch exception !.

https://github.com/fbertram/TuringTrader/blob/dda16009903b3caab66afc3200c7152baeb506c9/TuringTrader.Simulator/DataSources/DataSourceFred.cs#L332

Change to 

```c#
value = double.Parse(valueString, CultureInfo.InvariantCulture);
```


Best Regards, Eric

**Comment by fbertram** [comment]
thanks a lot for looking into this, your help is highly appreciated.

I just released v0.12b2, which includes the fix. See here: https://www.turingtrader.org/download/

Let me know if this works for you.

**Comment by TightLinesOfCode** [comment]
This is related to the JSON Parsing in NewtonSoft

It will automatically change the time zone to something you may not want.    You will need to address this for sure in your application

This is a common problem and the newtonsoft developers don’t want to change it.

https://www.niceonecode.com/Question/20518/Json.NET-Deserialize-Object-change-the-timezone-to-local-time

**Comment by fbertram** [comment]
thanks. Right now, the issue seems to be more related to the parsing of doubles than date/ time. However, I will keep that in mind in case other problems w/ localization pop up.
