### ISSUE TITLE
Do you have an example showing how to use csv Files?

### ISSUE THREAD

**Issue by quantcn** [fbertram/TuringTrader#6]
My ohlcv datas are in csv files. I want to use them to do backtest. I read 
https://www.turingtrader.org/help/articles/DataSetup.html, but still cannot figure out. Could you make a working example?
Thank you for your great work.

**Comment by fbertram** [comment]
To access CSV data, you need a Data Source Descriptor (.inf file) for each data source (asset) you want to bring in. The project includes an example for SPX option quotes in CSV format. 

Find the data here:
https://github.com/fbertram/TuringTrader/blob/master/Data/Data/%24SPX.options/SPX_20180102.csv

And the Data Source descriptor here:
https://github.com/fbertram/TuringTrader/blob/master/Data/%24SPX.options.inf

If you need more help, please paste a few lines from the top of your CSV, and I am happy to assist in setting up your descriptors.

**Comment by fbertram** [comment]
I haven't heard from you since - did you need more help? If so, please re-open the ticket.

**Comment by qtbgo** [comment]
Thank you for your response. I tried to modify demo04_options.cs below. But did not succeed. I am not familiar with C#.
And don't know if I am in the right direction. Any suggestion?
`namespace TuringTrader.Demos
{
    public class Demo04_Options : Algorithm
    {
        #region internal data
        private Plotter _plotter = new Plotter();
        private readonly string _template = "SimpleChart";
        private readonly string _underlyingNickname = "$SPX";
#if USE_FAKE_QUOTES
        private readonly string _optionsNickname = "$SPX.fake.options";
#else
        private readonly string _optionsNickname = "$SPX.options";
#endif`

**Comment by fbertram** [comment]
Hello Qtbgo,
I assume that you are still experimenting with bringing in CSV data? Here is what I would suggest:

1) Start experimenting with demo 01 because it is way simpler than the options demo. I only referred to that demo because it makes use of CSV data. See here: https://github.com/fbertram/TuringTrader/blob/master/Algorithms/Demo%20Algorithms/Demo01_Indicators.cs

2) in line 43, you see the following code:
`private readonly string _instrumentNick = "$SPX";`
Change "$SPX" to whatever the nickname of the data set you want to bring in might be. The nickname can match the ticker symbol, but it does not have to. For the sake of this example, let's use "QTBGO".

3) create a data source descriptor. Read the article here: https://www.turingtrader.org/help/articles/DataSetup.html
Save this file in C:\Users\[your home folder]\Documents\TuringTrader\Data\QTBGO.inf
For a simple set of OHLCV data, you can use a data source descriptor like this:
```
name=QTBGO's Fancy Data Set
ticker=QTBGO
dataPath=Data\QTBGO
date={1:MM/dd/yyyy}
time=16:00
open={2:F2}
high={3:F2}
low={4:F2}
close={5:F2}
volume={6}
```

4) Place your CSV data in C:\Users\[your home folder]\Documents\TuringTrader\Data\Data\QTBGO
With the descriptor above, you should be able to read data of the following format:
date,open,high,low,close,volume,
05/15/2006,15.00,15.00,15.00,15.00,0,
05/16/2006,14.99,14.99,14.99,14.99,0,
05/17/2006,14.76,14.76,14.76,14.76,0,
05/18/2006,14.65,14.65,14.65,14.65,0,
05/19/2006,14.69,14.69,14.69,14.69,0,

5) tweak your data source descriptor as needed. Of particular concern is the date format. Learn more here about how C# parses dates: https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

Qtbgo, I am closing this ticket because it is not referring to an issue with TuringTrader, but is a question. I am a bit concerned by your statement " I am not familiar with C#". To be successful with TuringTrader, you need to possess solid coding skills in C#, and I can't help you get there. 

Best regards, Felix

**Comment by qtbgo** [comment]
thank you very much, it works.

**Comment by fbertram** [comment]
perfect, thanks for letting me know.

**Comment by qtbgo** [comment]
cool！
