### ISSUE TITLE
Demo03_Portfolio - Can't load Yahoo data

### ISSUE THREAD

**Issue by matcha21** [fbertram/TuringTrader#9]
The following message pops up when I run the script Demo03 on my computer:

EXCEPTION: DataSourceYahoo: failed to load quotes for XLY, No such host is known. No such host is known.   at TuringTrader.Simulator.DataSourceCollection.DataSourceYahoo.LoadData(DateTime startTime, DateTime endTime) in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader.Simulator\DataSources\DataSourceYahoo.cs:line 421
   at TuringTrader.Simulator.SimulatorCore.get_SimTimes()+MoveNext() in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader.Simulator\Core\SimulatorCore.cs:line 446
   at TuringTrader.Demos.Demo03_Portfolio.Run() in C:\Users\Matcha\Documents\TuringTrader\Algorithms\Demo Algorithms\Demo03_Portfolio.cs:line 75
   at TuringTrader.MainWindow.<>c__DisplayClass35_0.<RunButton_Click>g__uiThread|1() in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader\MainWindow.xaml.cs:line 540
finished algorithm Demo03_Portfolio after 4.2 seconds
EXCEPTION: Plotter: no data to plot   at TuringTrader.Simulator.Plotter.OpenWith(String pathToTemplateFile) in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader.Simulator\Core\Plotter.cs:line 239
   at TuringTrader.Demos.Demo03_Portfolio.Report() in C:\Users\Matcha\Documents\TuringTrader\Algorithms\Demo Algorithms\Demo03_Portfolio.cs:line 161
   at TuringTrader.MainWindow.<ReportButton_Click>b__36_0() in C:\Users\Felix\Documents\Trading\TuringTrader\TuringTrader\TuringTrader\MainWindow.xaml.cs:line 593

**Comment by matcha21** [comment]
For information, I managed to run the script successfully with data from Tiingo.

**Comment by fbertram** [comment]
Hello matcha21, 

Thanks a lot for reporting. It seems that Yahoo has changed its API in the past week, which is why this is no longer working. I need to look into this and see if there is another way to retrieve the data.

Please note the following:
(1) This is a hack. The interface is not officially documented by Yahoo, and they clearly don't want people to use it for free.
(2) Data downloaded from Yahoo always suffered from some spurious glitches; I believe they intentionally tainted the data.
(3) I might not be able to bring the Yahoo data source back - I need to look deeper into this and see if there is another way to bring this back

The Tiingo interface does not suffer from these restrictions as it is based on an officially supported API. Their data are better quality and their free tier is quite generous.


Best regards, Felix

**Comment by matcha21** [comment]
Hi Felix,

Thanks a lot for the reply, I'll just stick to Tiingo data then. I am
getting familiar with Turing Trader and C#, since I come from Backtrader
and am more used to Python. I really like the features that Turing Trader
can offer. I'll continue posting if I see something else that needs support.

Kind regards,

Mathieu

Le sam. 22 mai 2021 à 13:21, Felix Bertram ***@***.***> a
écrit :

**Comment by fbertram** [comment]
Mathieu - it seems Yahoo just changed the URL of their API, but everything else seems to have stayed the same. Based on this I have fixed the Yahoo data source on the development branch. I hope to build a new release version next week.

Let me know if you need anything else.

Best regards, Felix
